### ISSUE TITLE
Can nodes be arranged in non-interactive way?

### ISSUE THREAD

**Issue by vanous** [Leonardo-Pike-Excell/node-arrange#3]
Thank you for all the awesome work on this! If i provide list of nodes to the operator (or rather, to the modified class itself), do you know if the arrangement can happen even if the `context.space_data.edit_tree` is not available? I have modified the routine,  removed the "selected" filter, but at this point it only arranges the nodes on x axis and i would like to know if it makes sense to spend more the time on it... if perhaps there isn't something which would prevent it to work in situation when the node editor is not open.

[Here is the very slightly modified class](https://github.com/open-stage/blender-dmx/blob/arrange/node_arranger.py), I just removed the variables declared as global. [And here i use it.](https://github.com/open-stage/blender-dmx/blob/arrange/fixture.py#L543)

Thank you so much for your time and expertise.

**Comment by Leonardo-Pike-Excell** [comment]
`node_tree` should work fine in place of `context.space_data.edit_tree`. But other things may cause issues:  

1. If nodes have been added to the node tree without the node editor open, `node.dimensions` will be wrong since it only gets evaluated on UI redraw. 
2. `bpy.ops.transform.translate()` may fail without the proper context. (If you know the node trees won’t have frames or locations far from (0, 0), this shouldn’t be a problem.)

I can’t think of anything else that could case issues, but there may be more gotchas relating to context and UI redraw.
