### ISSUE TITLE
Please save Blender! About what I consider to be an extremely important feature!

### ISSUE THREAD

**Issue by Mr-real-self** [Leonardo-Pike-Excell/node-arrange#6]
Hello, esteemed author!
Node Arrange is a great Blender plugin!
However, there are indeed some things that elude me and it should be better than it is!
At least, it should have “Super Center Alignment” and “Works on all selected objects”.

**I would like to make three suggestions, I guarantee that there are countless people who need these features, and they are definitely not niche.**

**[1. Add the ability to take effect on all objects]**
When the user selects multiple objects and clicks on the Arrange Selected button, the corresponding commands are automatically executed on the selected objects one by one to ensure that all selected objects take effect.
I do not need to say the specific logic, you must know better than me, which involves a problem, please look at the second proposal to see the third proposal.

**[2. Add “Super Center Alignment” function]**
When the user clicks the Arrange Selected button, every node of an object after the implementation of alignment, sorting and other commands, automatically insert a “Super Center Align” command, the function is to first check the object “by all the nodes of the box composed of the upper, lower, left, right border ”, and then as a whole, the center of the whole moved to the origin (0,0).
After the realization of each object, “the overall center of all nodes” will be the origin (0,0), no longer need to press the “Home” key every day.

**[3. Add intelligent selection of all functions]**
This is a suggestion related to the first suggestion.
When the user selects an object, but does not select any node, click the Arrange Selected button will first automatically select all the nodes of the object, and then perform other commands.
When the user selects multiple objects, regardless of whether the user selects nodes or not, clicking the Arrange Selected button will first automatically select all nodes of each object before executing other commands.

I still have suggestions, if you are willing to implement these what I consider to be the most basic features, I will continue to submit suggestions once they are implemented, thank you!

**You are really great, please make Blender great again!**

**Comment by Leonardo-Pike-Excell** [comment]
Hi, thanks for the suggestions.

**1.**

If I understand you correctly, you want the “Selected” in “Arrange Selected” to double as selected nodes, and every node tree in the selected objects. I think this would be confusing. If the user wants to arrange only the current tree, they have to remember to deselect all objects first. It’s not clear that “Selected” refers to two types of things, and the node editor sidebar is meant to be responsible only for the current node tree.

While I’m planning on investigating mass arranging node trees, it requires:
1. Improved performance (for which I’m working on an overhaul that should give higher quality results and be significantly faster).
2. Fixing issues with affecting node trees without the node tree open (which might not even be fixable due to how Blender currently works).


**2.**

I assume you want the centre of the bounding box of all nodes, for every node tree, to be made the same. This is a good idea, and I’ll try to eventually add this.


**3.**

My issues with 1. apply here too. And for selecting all nodes when none are selected, I would rather keep the behaviour of _Arrange Selected_ consistent.

**Comment by ugorek000** [comment]
@Mr-real-self Would you be satisfied with such functionality?
https://blenderartists.org/uploads/default/original/4X/d/f/4/df46446536844f63dee3c6505dfddb9066a25c70.gif
https://blenderartists.org/uploads/default/original/4X/6/4/4/644d42f7792b464749564935a30d0c8781600b57.gif
